image: docker:24.0.7-dind

options:
  docker: true

definitions:
  services:
    docker:
      memory: 2048
  caches:
    sonar: ~/.sonar
    maven: ~/.m2

pipelines:
  pull-requests:    
    '**':
      - step:
          name: Build and Test PR
          services:
            - docker
          caches:
            - docker
          script:
            # Create test results directory
            - mkdir -p test-results
            - chmod -R 777 test-results
            # Disable BuildKit
            - export DOCKER_BUILDKIT=0
            - export COMPOSE_DOCKER_CLI_BUILD=0
            # Docker commands
            - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - docker compose build
            # Start DB with logging
            - docker compose up -d db
            - sleep 10
            # Check DB logs
            - docker compose logs db
            - sleep 100
            # Run tests
            - docker compose run test || { docker compose logs db; exit 1; }
            # Cleanup
            - docker compose down
      - step:
          name: SonarQube analysis
          image: maven:3.8.7-eclipse-temurin-11
          caches:
            - maven
            - sonar
          script:
            - curl -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            - unzip sonar-scanner.zip
            - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin
            - sonar-scanner \
                -Dsonar.projectKey=ist-challenge \
                -Dsonar.sources=. \
                -Dsonar.host.url=${SONAR_URL} \
                -Dsonar.login=${SONAR_TOKEN}

  branches:
    main:
      - step:
          name: Build, Test and Deploy
          services:
            - docker
          caches:
            - docker
          script:
            # Create test results directory
            - mkdir -p test-results
            - chmod -R 777 test-results
            # Disable BuildKit
            - export DOCKER_BUILDKIT=0
            - export COMPOSE_DOCKER_CLI_BUILD=0
            # Docker commands
            - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - docker compose build
            # Start DB with logging
            - docker compose up -d db
            - sleep 10
            # Check DB logs
            - docker compose logs db
            - sleep 100
            # Run tests
            - docker compose run test || { docker compose logs db; exit 1; }
            
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER_IP
                PORT: $SSH_PORT
                MODE: non-interactive
                COMMAND: |
                  cd ${PROJECT_PATH}
                  git pull origin main
                  docker compose down
                  docker compose up -d --build
                  docker image prune -f