image: atlassian/default-image:latest  # Changed base image

definitions:
  services:
    docker:
      memory: 2048
  caches:
    sonar: ~/.sonar

pipelines:
  pull-requests:    
    '**':
      - step:
          name: Build and Test PR
          services:
            - docker
          script:
            # Add Docker's official GPG key
            - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            
            # Add Docker repository
            - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            
            # Install Docker and Docker Compose
            - apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            
            # Start Docker service
            - service docker start
            
            - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - docker-compose build
            - docker-compose up -d db
            - sleep 10
            - docker-compose run test
      - step:
          name: SonarQube analysis
          image: maven:3.8.7-eclipse-temurin-11
          caches:
            - maven
            - sonar
          script:
            - curl -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            - unzip sonar-scanner.zip
            - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin
            - sonar-scanner \
                -Dsonar.projectKey=ist-challenge \
                -Dsonar.sources=. \
                -Dsonar.host.url=${SONAR_URL} \
                -Dsonar.login=${SONAR_TOKEN}

  branches:
    main:
      - step:
          name: Build, Test and Deploy
          services:
            - docker
          script:
            # Add Docker's official GPG key
            - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            
            # Add Docker repository
            - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            
            # Install Docker and Docker Compose
            - apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            
            # Start Docker service
            - service docker start
            
            - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - docker-compose build
            - docker-compose up -d db
            - sleep 10
            - docker-compose run test
            
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER_IP
                PORT: $SSH_PORT
                MODE: non-interactive
                COMMAND: |
                  cd ${PROJECT_PATH}
                  git pull origin main
                  docker-compose down
                  docker-compose up -d --build
                  docker image prune -f