image: docker:20.10.16

options:
  docker: true

definitions:
  services:
    docker:
      memory: 2048
  caches:
    sonar: ~/.sonar

pipelines:
  pull-requests:
    'main':
      - step:
          name: Build and Test
          services:
            - docker
          caches:
            - docker
          script:
            - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - docker-compose build
            - docker-compose up -d db
            - sleep 10  # Give database time to start
            - docker-compose run test
      - step:
          name: SonarQube analysis
          image: maven:3.8.7-eclipse-temurin-11
          caches:
            - maven
            - sonar
          script:
            # Install SonarScanner
            - curl -Lo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            - unzip sonar-scanner.zip
            - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin
            # Run SonarQube analysis
            - sonar-scanner \
                -Dsonar.projectKey=ist-challenge \
                -Dsonar.sources=. \
                -Dsonar.host.url=${SONAR_URL} \
                -Dsonar.login=${SONAR_TOKEN}

  branches:
    main:
      - step:
          name: Build, Test and Deploy
          services:
            - docker
          caches:
            - docker
          script:
            - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            - docker-compose build
            - docker-compose up -d db
            - sleep 10
            - docker-compose run test
            
            # Deploy automatically if tests pass
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SERVER_IP
                PORT: $SSH_PORT
                MODE: non-interactive  # Add this for non-interactive mode
                COMMAND: |
                  cd ${PROJECT_PATH}  # Use variable instead of hardcoded path
                  git pull origin main
                  docker-compose down
                  docker-compose up -d --build
                  docker image prune -f  # Clean up unused images