version: '3.8'

services:
  node_app:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env.prod
    command: npm run start
    depends_on:
      - db
