version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "3456:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  python_api:
    build: 
      context: ./python_app
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/python_tododb
      - JWT_SECRET_KEY=your_jwt_secret_key_change_in_production
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PORT=5002
    volumes:
      - ./python_app:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  node_api:
    build:
      context: ./node_app
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=node_tododb
      - NODE_ENV=development
    volumes:
      - ./node_app:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=password
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  test:
    profiles:
      - test
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
      - SONAR_TOKEN=${SONAR_TOKEN}
      - SONAR_HOST_URL=http://sonarqube:9000
    volumes:
      - ./:/app
      - test-results:/app/test-results
    depends_on:
      - db
      - sonarqube
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  test-results: