version: '3.8'

services:
  node_api:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./node_app:/app

  python_api:
    environment:
      - FLASK_DEBUG=0
    volumes:
      - ./python_app:/app

  db:
    ports:
      - "3456:5432"
    command: ["postgres"]  # Remove logging in production