version: '3.8'

services:
  node_app:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./node_app:/app
      - /app/node_modules
    depends_on:
      - db
