FROM node:22.11.0-alpine AS base

# Add wait-for script
ADD https://github.com/eficode/wait-for/raw/master/wait-for /wait-for
RUN chmod +x /wait-for

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Make our startup script executable
COPY scripts/start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 5001

# Use the startup script as default command
CMD ["/start.sh"]