FROM node:22.11.0-alpine AS base

ADD https://github.com/eficode/wait-for/raw/master/wait-for /wait-for
RUN chmod +x /wait-for

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

COPY scripts/start-prod.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 5001

CMD ["/start.sh"]