FROM node:22.11.0-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

COPY scripts/start.sh /start.sh
RUN chmod +x /start.sh

RUN npm run build
EXPOSE 5001
CMD ["npm", "start"]
